name: Deploy File to EC2 Instance

on:
  push:
    branches:
      - main  # Trigger the workflow when changes are pushed to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest  # Use an Ubuntu runner

    steps:
    # Checkout repository code
    - name: Checkout repository
      uses: actions/checkout@v3

    # Set up SSH keys for EC2 access
    - name: Set up SSH key
      run: |
        mkdir -p ~/.ssh
        echo "$EC2_SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
      env:
        EC2_SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}

    # Add EC2 host to known hosts to prevent SSH authenticity check
    - name: Add EC2 to known hosts
      run: |
        ssh-keyscan -H ${{ secrets.EC2_PUBLIC_IP }} >> ~/.ssh/known_hosts
      env:
        EC2_PUBLIC_IP: ${{ secrets.EC2_PUBLIC_IP }}

    # Copy a file to EC2
    - name: Copy file to EC2
      run: |
        scp -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no myfile.txt ubuntu@${{ secrets.EC2_PUBLIC_IP }}:/home/ubuntu/
      env:
        EC2_PUBLIC_IP: ${{ secrets.EC2_PUBLIC_IP }}

    # Run commands on EC2 (Optional)
    - name: Run commands on EC2
      run: |
        ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
          echo "This is a new file created by GitHub Actions!" > /home/ubuntu/newfile.txt
        EOF
      env:
        EC2_PUBLIC_IP: ${{ secrets.EC2_PUBLIC_IP }}
