name: Deploy File to EC2 Instance

on:
  push:
    branches:
      - main  # Change this to your preferred branch if different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Set up SSH key to connect to EC2 instance
    - name: Set up SSH key
      run: |
        mkdir -p ~/.ssh
        echo "$EC2_SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
      env:
        EC2_SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}

    # Step 3: Set SSH known hosts (This prevents SSH warnings about authenticity)
    - name: Add EC2 to known hosts
      run: |
        ssh-keyscan -H ${{ secrets.EC2_PUBLIC_IP }} >> ~/.ssh/known_hosts

    # Step 4: Copy file to EC2 instance
    - name: Copy file to EC2
      run: |
        scp -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no myfile.txt ubuntu@${{ secrets.EC2_PUBLIC_IP }}:/home/ubuntu/
        # Replace 'myfile.txt' with the file you want to copy, and adjust the path if needed
      env:
        EC2_PUBLIC_IP: ${{ secrets.EC2_PUBLIC_IP }}

    # Step 5: Optional: Run commands on EC2 (e.g., creating a new file)
    - name: Run commands on EC2
      run: |
        ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
          echo "This is a new file created by GitHub Actions!" > /home/ubuntu/newfile.txt
        EOF
      env:
        EC2_PUBLIC_IP: ${{ secrets.EC2_PUBLIC_IP }}
