name: Deploy File to EC2 Instance

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Set up SSH key for EC2 access
    - name: Set up SSH key
      run: |
        mkdir -p ~/.ssh
        echo "$EC2_SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa  # Ensure private key has correct permissions
      env:
        EC2_SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}

    # Step 3: Add EC2 instance to known hosts
    - name: Add EC2 to known hosts
      run: |
        ssh-keyscan -H ${{ secrets.EC2_PUBLIC_IP }} >> ~/.ssh/known_hosts
      env:
        EC2_PUBLIC_IP: ${{ secrets.EC2_PUBLIC_IP }}

    # Step 4: Copy file to EC2 with verbose output
    - name: Copy file to EC2 with verbose output
      run: |
        scp -vvv -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no myfile.txt ubuntu@${{ secrets.EC2_PUBLIC_IP }}:/home/ubuntu/
      env:
        EC2_PUBLIC_IP: ${{ secrets.EC2_PUBLIC_IP }}

    # Step 5: Run commands on EC2 (optional)
    - name: Run commands on EC2
      run: |
        ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
          echo "This is a new file created by GitHub Actions!" > /home/ubuntu/newfile.txt
        EOF
      env:
        EC2_PUBLIC_IP: ${{ secrets.EC2_PUBLIC_IP }}
